### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#156]
This is a list of potential improvements for the dashboard:

### Done

- [x] Generalize input -> #163 
  - Input from `runs.yaml`
  - ~Input from Jintrac run directories, take IDS from `jetto.jset`~, this is a out of scope for the moment
  - Input db, shot, run numbers directly
  - ~Command-line interface to specify inputs~
- [x] Calculate confidence interval and store to new IDS -> #164 
  - This can be a form where we specify:
    1. Name of IDS to save to (db, shot, run)
    2. Name of template IDS, copy all data from this IDS and overwrite data with confidence, fill lower/upper bounds.
    3. Time must be interpolated (use template IDS?)
    4. Rho_tor must be interpolated (use template IDS?)
- [x] Default to `rho_tor_norm` for x instead of `rho_tor`  -> #163 
- [x] Add comment to documentation that the dashboard needs a reasonably recent browser (i.e. not the one on Gateway) -> #186
- [x] Refactor plotting code so that it can be used in a command line tool
    - Perhaps this can replace `duqtools plot`, i.e. `duqtools plot -u g2ssmee -d jet -s 91234 -r 8010 <ids>` -> #195 

### Todo

- [x] Find way to set `_error_upper` if the template is an empty array -> #204 
- [x] Finish up merge functionality in dashboard -> #206
- [x] Refactor merging code so that it can be used in a command line tool
    - `duqtools combine`? -> #206
- [x] Do proper error propagation using `_error_upper` / `_error_lower` from input IDS data
    - Start simple: https://en.wikipedia.org/wiki/Propagation_of_uncertainty
        - $\bar{X} = \frac{1}{n} (X_1 + X_2 + ... + X_n)$
        - $\Delta X = \frac{1}{n} \sqrt{\Delta X_1^2 + \Delta X_2^2 + ... + \Delta X_n^2}$
    - Not needed, Jetto does not produce error bars by itself so no need for error propagation
- [x] Dealing with outliers -> can be done via `data.csv`
