### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#159]
This issue tracks enhancements to the documentation.

- [x] duqtools.yaml: system -> #162 
- [x] duqtools.yaml: workspace -> #162 
- [x] duqtools.yaml: create/data location? -> #162 
- [x] #160
