### ISSUE TITLE
`pip install duqtools`

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#188]
To make the code easier to install, we should upload the packages to pypi. This can be done via a github action that is triggered when a new release is made.

This issue tracks the progress and necessary steps.

## Todo:

- [x] Make github action
- [x] Update manifest.in and check that all files are included (.md / .txt mainly)
- [x] Changes to `pydantic-yaml` must be available on pypi (cannot have links in the setup.cfg)
- [x] Use [build](https://pypa-build.readthedocs.io/en/latest/) to build using `pyproject.toml`, i.e. `python -m build --no-isolation`
- [x] Move `dash` and `duqtools` under `src/` so that it is easily included as recommended [here](https://setuptools.pypa.io/en/latest/userguide/datafiles.html#data-files-support)
  - Possibly `ln -s src/dash/ dash/`
- [x] Make a first manual upload to pypi to generate an access token

**Comment by stefsmeets** [comment]
Example GA:
https://github.com/hpgem/nanomesh/blob/master/.github/workflows/publish.yml

**Comment by stefsmeets** [comment]
Now available on Pypi: https://pypi.org/project/duqtools/0.1.0/ 🎉
