### ISSUE TITLE
Duqtools Init should be pre-defined, so we can define how it looks

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#311]
Load the config from a config file with defaults.

`duqtools init` will simply copy the file to the local directory.

Pydantic can still be used to validate the config. We can also read it to populate the pydantic model with defaults, so we can remove all defaults from the code in the model definition. We can re-use the config also to show in the documentation.

**Comment by stefsmeets** [comment]
### Todo

- [ ] Move `duqtools.yaml` to data directory
- [ ] `duqtools init` copies config from data directory to local directory
- [ ] Use this config to load defaults from
- [ ] Can we import this config into the docs?
