### ISSUE TITLE
Automate setting up inputs for Jetto

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#4]
We need to automate reading / writing the files below to be able to take an existing run and modify it.

Files to parse/modify:
- [x] `.llcmd`: bash script, starts simulation -< #44 
- [x] `jetto.jset`: JAVA settings file, contains JAMS params, parse for settings -> #32
- [x] `jetto.in`: Fortran namelist, contains JETTO params, write/update simulation input -> #29 

Note: `jintrac_imas_config.cfg` is written by `rjettov` and overwritten every time.

Existing `scanAPI` (== `jetto-pythontools`) package can carry out some of this work, but it is not IMAS compatible. Should be looked at.

**Comment by stefsmeets** [comment]
Package for reading namelists: 
- [f90nml](https://f90nml.readthedocs.io/en/latest/)

**Comment by stefsmeets** [comment]
Hi @jcitrin, thanks for the input! This is indeed for automating the generation of a new `jetto.in`. If the header is necessary for jetto, then I'll have to add an extra step when reading / writing the jetto input :-)

**Comment by stefsmeets** [comment]
I just realized that `jetto-pythontools` has a module for reading/writing jetto namelists. It also uses `f90nml`, and it's not that different from what we currently have. The main advantage is that it reads the headers. It's licenced under MIT so we can re-use part of it if necessary.

code: https://gitlab.com/jintrac/jetto-pythontools/-/blob/master/jetto_tools/namelist.py
docs: https://jintrac.gitlab.io/jetto-pythontools/namelist.html

**Comment by stefsmeets** [comment]
This has now been implemented and seems to work as expected.
