### ISSUE TITLE
Implement operations on IDS profiles

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#58]
This issue keeps track of the type of operations to be applied to the IDS profile.

These operations are applied in the `create` step.

## Simple operations

- [x] Simple numpy arithmetic operations
  - [x] Multiplication, i.e. (e.g. x * [0.75 , 0.95 , 1.05 , 1.25])  -> #63
  - [x] Addition, (e.g. for Zeff: x + [0.2,0.4,0.6,0.8]) -> #63
    - Note that a user needs information on absolute values of profiles for this to make sense
- [x] #307

## Operations based on error quantities

- [x] Addition/subtraction by factors of sigma (e.g. x + [0.25sigma, 0.5sigma, 1sigma, 2sigma]) -> #187
  - see https://github.com/CarbonCollective/fusion-dUQtools/issues/58#issuecomment-1188741966
- [x] Allow for symmetric and asymmetric errors
- [x] Sample based on error distribution, e.g. gaussian distribution sampling, must be able to set total number of runs (=number of samples to take) -> #145

## Sampling methodology

To think about: sampling methodology. Especially if multiple profiles are being modified. 

- [x] Simple full lattice (Cartesian product, as currently implemented in `matrix`)
- [x] Smarter samplers -> #71
    - [x] Latin Hypercube
    - [x] Low discrepancy sequences (Sobol)
    - [x] Halton sampler

**Comment by stefsmeets** [comment]
Hi @aaronkho @jcitrin ,
I'm implementing sampling a distribution around the IDS using the error bars as the bounds. I wanted to check what you meant by 'asymmetric' sampling, i.e. if the upper and lower bounds are different. Seems to me like you would get a very 'disjoint' distribution by using this, so I'm wondering if this is the intent. 

This post on SO illustrates well what I mean: https://stackoverflow.com/a/53048572

**Comment by stefsmeets** [comment]
Relevant function in scipy? -> [scipy.stats.skewnorm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skewnorm.html)

**Comment by aaronkho** [comment]
The scipy skewnorm seems like exactly what we want here. However, I am
unsure how to convert the asymmetric errors into the "a" parameter needed
by the function. In this case, we can interpret the upper and lower error
values as the 16th and 84th percentiles, respectively.

**Comment by stefsmeets** [comment]
Yeah, exactly, for the symmetric error I have been assuming that the error describes the sigma of the data.

For asymmetric distributions, this is what the data model documentation has to say about the error values:

> By convention, only the upper error node should be filled in case of symmetrical error bars. The upper and lower errors are absolute and defined positive, the effective values of the data will be within the interval [data-data_error_lower, data+data_error_upper]. Thus whatever the sign of data, data_error_lower relates to the lower bound and data_error_upper to the upper bound of the error bar interval.

The data I have worked with so far does not seem to have any ids with `*_error_lower`. So we can pick up on this later. 

In any case, it would be good to know how the asymmetric error description is defined. And also what the the data represents in terms of mode, mean, or median.

**Comment by stefsmeets** [comment]
How to interpret lower/upper:

1. Value itself is the mean
2. error_upper -> $1\sigma^+$, (~84th percentile)
3. error_lower -> $1\sigma^-$, (~16th percentile)
4. How to calculate `a`?

**Comment by stefsmeets** [comment]
Some feedback from @aaronkho , seems like we implemented the IDS sampler in the wrong way, i.e. no double sampling.

For now: we should sample the whole range:
  - from -3 sigma to +3 sigma with 10 steps
  - support lists of numbers to multiply with sigma, [-2, -1, 0, 1, 2] * sigma

For later: we should support sampling discrete and continuous distributions:
  - Currently we support sampling a discrete distribution (i.e. list)
  - Latin-Hypercube should be able to sample a distribution
  - Distribution sampling should be weighted?
  - Rename matrix -> dimensions
  - Allow dimensions to be excluded from latin-hypercube sampling

**Comment by stefsmeets** [comment]
Most of the work in this issue has been completed. I converted the remaining open item to a new issue: https://github.com/CarbonCollective/fusion-dUQtools/issues/307
